---

- name: Set MySQL root password before Package Installation
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{sql_root_password | quote}}' vtype='password'
  changed_when: false # Suppress "changed" status
  when: mariadb is undefined

- name: Confirm MySQL root passwort before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{sql_root_password | quote}}' vtype='password'
  changed_when: false # Suppress "changed" status
  when: mariadb is undefined

- name: Install MySQL packages and tools
  apt: pkg={{ item }} update_cache=yes state=present
  when: mariadb is undefined
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libdbi-perl
    - libdbd-mysql-perl
  notify:
    - start mysql/mariadb server

- name: Set MariaDB root password before Package Installation
  debconf: name='mariadb-server' question='mariadb-server/root_password' value='{{sql_root_password | quote}}' vtype='password'
  changed_when: false # Suppress "changed" status
  when: mariadb is defined

- name: Confirm MariaDB root passwort before installing
  debconf: name='mariadb-server' question='mariadb-server/root_password_again' value='{{sql_root_password | quote}}' vtype='password'
  changed_when: false # Suppress "changed" status
  when: mariadb is defined

- name: Install MariaDB packages and tools
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000 state=present
  when: mariadb is defined
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb
  notify:
    - start mysql/mariadb server

- name: Push client configuration for root user
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

